version: '3'
services: 
    web-app:
        build: ./api-nasa/
        volumes:
            - ./api-nasa/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: olaf
            POSTGRES_PASSWORD: 1234

