version: '3'
services: 
    product-service:
        build: ./api-nasa/
        volumes:
            - ./api-nasa/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: alisson123

